name: cryptrend
description: "CrypTrend is a crypto app"

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  shadcn_ui: ^0.28.5
  http: ^1.1.0
  shared_preferences: ^2.5.3
  flutter_requery: ^0.1.16
  firebase_core: ^4.1.0
  flutter_local_notifications: ^19.4.2
  firebase_messaging: ^16.0.1
  flutter_dotenv: ^6.0.0
  flutter_stripe: ^12.0.2
  flutter_launcher_icons: ^0.14.4
  flutter_native_splash: ^2.4.6
  supabase_flutter: ^2.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0

flutter:

  uses-material-design: true
  assets:
    - assets/icon/
    - .env

flutter_native_splash:
  color: "#080c1c"
  image: "assets/icon/icon-transparent.png"
  android: true
  ios: true

flutter_icons:
  android: true
  ios: true
  image_path_android: "assets/icon/icon.png"
  image_path_ios: "assets/icon/icon.png"
  adaptive_icon_background: "#080c1c"       
  adaptive_icon_foreground: "assets/icon/icon-transparent.png"